const money=n=>`₹${n.toLocaleString('en-IN')}`;
const getCart=()=>JSON.parse(localStorage.getItem('marketly_cart')||'[]');
const saveCart=c=>{localStorage.setItem('marketly_cart',JSON.stringify(c));updateCartCount()};
const updateCartCount=()=>{const e=document.querySelector('.cart-count');if(e)e.textContent=getCart().reduce((s,x)=>s+x.qty,0)};
function header(){return `<header class="site-header"><nav class="nav"><a class="logo" href="index.html">market<span>ly.</span></a><div class="nav-links"><a href="index.html">Home</a><a href="products.html">Products</a><a href="cart.html" class="cart-link">Cart (<span class="cart-count">0</span>)</a><a href="login.html">Login</a></div><a class="mobile-menu" href="cart.html">🛒</a></nav></header>`}
function footer(){return `<footer class="site-footer">© 2026 Marketly · Frontend demo store</footer>`}
document.getElementById('header')&&(document.getElementById('header').innerHTML=header());
document.getElementById('footer')&&(document.getElementById('footer').innerHTML=footer());
updateCartCount();

function productCard(p){return `<article class="product-card"><div class="product-image" onclick="location.href='product.html?id=${p.id}'">${p.emoji}</div><div class="product-body"><span class="product-id">PRODUCT ID: ${p.id}</span><h3>${p.name}</h3><p>${p.category}</p><div class="price">${money(p.price)}</div><div class="card-actions"><button class="small-btn" onclick="location.href='product.html?id=${p.id}'">View</button><button class="small-btn primary" onclick="addToCart(${p.id})">Add to cart</button></div></div></article>`}
function addToCart(id){const c=getCart(),x=c.find(i=>i.id===id);x?x.qty++:c.push({id,qty:1});saveCart(c);alert('Product added to cart!')}
function initHome(){document.getElementById('categories').innerHTML=CATEGORIES.map(c=>`<div class="category" onclick="location.href='products.html?category=${encodeURIComponent(c.name)}'"><div class="cat-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p></div>`).join('');document.getElementById('featured').innerHTML=PRODUCTS.slice(0,8).map(productCard).join('')}
if(document.getElementById('featured'))initHome();

let selectedCategory=new URLSearchParams(location.search).get('category')||'All';
function initProducts(){const filters=['All',...CATEGORIES.map(c=>c.name)];document.getElementById('categoryFilters').innerHTML=filters.map(x=>`<button class="filter ${x===selectedCategory?'active':''}" onclick="filterProducts('${x}')">${x}</button>`).join('');renderProducts()}
function filterProducts(c){selectedCategory=c;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.textContent===c));renderProducts()}
function renderProducts(){let list=selectedCategory==='All'?PRODUCTS:PRODUCTS.filter(p=>p.category===selectedCategory);const sort=document.getElementById('sort')?.value;if(sort==='low')list=[...list].sort((a,b)=>a.price-b.price);if(sort==='high')list=[...list].sort((a,b)=>b.price-a.price);if(sort==='name')list=[...list].sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('productList').innerHTML=list.map(productCard).join('')}
document.getElementById('sort')?.addEventListener('change',renderProducts);

function initProductDetail(){const id=Number(new URLSearchParams(location.search).get('id'));const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];document.getElementById('productDetail').innerHTML=`<div class="detail"><div class="detail-image">${p.emoji}</div><div><span class="eyebrow">${p.category}</span><h1>${p.name}</h1><div class="product-id">PRODUCT ID: ${p.id}</div><div class="detail-price">${money(p.price)}</div><p class="description">${p.description}</p><div class="qty"><button onclick="changeDetailQty(-1)">−</button><b id="detailQty">1</b><button onclick="changeDetailQty(1)">+</button></div><button class="btn" onclick="addDetailToCart(${p.id})">Add to cart</button></div></div>`}
let detailQty=1;function changeDetailQty(n){detailQty=Math.max(1,detailQty+n);document.getElementById('detailQty').textContent=detailQty}
function addDetailToCart(id){const c=getCart(),x=c.find(i=>i.id===id);x?x.qty+=detailQty:c.push({id,qty:detailQty});saveCart(c);location.href='cart.html'}

function renderCart(){const el=document.getElementById('cartContent'),c=getCart();if(!c.length){el.innerHTML=`<div class="empty"><h2>Your cart is empty</h2><p>Add some products to get started.</p><a class="btn" href="products.html">Browse products</a></div>`;return}let subtotal=0;const items=c.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);subtotal+=p.price*i.qty;return `<div class="cart-item"><div class="cart-thumb">${p.emoji}</div><div class="cart-info"><span class="product-id">PRODUCT ID: ${p.id}</span><h3>${p.name}</h3><p>${money(p.price)} each</p><div class="qty"><button onclick="updateQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="updateQty(${p.id},1)">+</button></div></div><div><b>${money(p.price*i.qty)}</b><br><button class="small-btn" onclick="removeItem(${p.id})">Remove</button></div></div>`}).join('');el.innerHTML=`<div class="cart-layout"><div>${items}</div><aside class="summary"><h3>Order summary</h3><div class="row"><span>Subtotal</span><b>${money(subtotal)}</b></div><div class="row"><span>Delivery</span><b>Free</b></div><div class="row total"><span>Total</span><b>${money(subtotal)}</b></div><a class="btn full" href="checkout.html">Purchase order</a></aside></div>`}
function updateQty(id,n){const c=getCart(),x=c.find(i=>i.id===id);x.qty=Math.max(1,x.qty+n);saveCart(c);renderCart()}
function removeItem(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}

function renderCheckout(){const el=document.getElementById('checkoutContent'),c=getCart();if(!c.length){el.innerHTML=`<div class="empty"><h2>No products to purchase</h2><a class="btn" href="products.html">Browse products</a></div>`;return}let total=0;const rows=c.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="row"><span>${p.name} × ${i.qty}</span><b>${money(p.price*i.qty)}</b></div>`}).join('');el.innerHTML=`<div class="checkout-layout"><section class="summary"><h2>Review order</h2>${rows}</section><aside class="summary"><h3>Purchase</h3><p class="muted">This demo does not collect payment details.</p><div class="row total"><span>Total</span><b>${money(total)}</b></div><button class="btn full" onclick="placeOrder()">Place order</button></aside></div>`}
function placeOrder(){if(!getCart().length)return;const id='ORD-'+Date.now().toString().slice(-8);const orders=JSON.parse(localStorage.getItem('marketly_orders')||'[]');orders.push({id,items:getCart(),date:new Date().toISOString()});localStorage.setItem('marketly_orders',JSON.stringify(orders));localStorage.removeItem('marketly_cart');location.href='success.html?order='+id}
function initSuccess(){document.getElementById('orderId').textContent='Order ID: '+(new URLSearchParams(location.search).get('order')||'ORD-DEMO')}

function initRegister(){document.getElementById('registerForm').addEventListener('submit',e=>{e.preventDefault();const user={name:document.getElementById('name').value,email:document.getElementById('email').value,password:document.getElementById('password').value};localStorage.setItem('marketly_user',JSON.stringify(user));alert('Account created successfully!');location.href='login.html'})}
function initLogin(){document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const u=JSON.parse(localStorage.getItem('marketly_user')||'null');const email=document.getElementById('email').value,password=document.getElementById('password').value;if(u&&u.email===email&&u.password===password){localStorage.setItem('marketly_logged_in','true');alert('Login successful!');location.href='index.html'}else alert('Invalid credentials. Please register first.')})}